### PR TITLE
Add a short description in README

### PR DESCRIPTION
**Pull request by tkf**

### CODE REVIEW

**Comment by pfitzseb** [comment]
The frontend/backend distinction is somewhat problematic imho: `ProgressLogging` is a frontend for the package author (because it is what they immediately interact with) but a backend for the user (who directly interacts with Juno/ProgressMeterLogging).

Looks good otherwise.

**Comment by aviatesk** [comment]
yep I had that impression too. Maybe "wrappper", "API interface" or some similar word would fit into this ?

**Comment by tkf** [comment]
I agree the terminology can be better.  Here is some brainstorming:

For progress bar "frontend":

* progress event source
* progress data source
* progress recorder
* progress definition
* progress logger [1]
* progress (event/record/log) emitter

For progress bar "backend":

* progress monitor
* progress display [2]
* progress viewer
* progress (event/record/log) handler

Notes:

[1] "progress logger" as a frontend kind of makes sense but it's the backend that defines `*Logger <: AbstractLogger` type (and the handler method `handle_message`).  So it may be confusing.

[2] "progress display" may be slightly confusing as we have the `display` stack with (somewhat) similar pluggable architecture.

Overall, I think "progress event source" and "progress monitor" sound good.

**Comment by tkf** [comment]
Actually, I think we can just say

> ProgressLogging.jl is a package for defining _progress logs_.

I think we can call the loop using `@progress` etc. a _progress log source_ but probably we don't need this term.

This makes me think that it's probably better to rename ProgressMeterLogging.jl to ConsoleProgressMonitor.jl. What do you think?

**Comment by pfitzseb** [comment]
> ProgressLogging.jl is a package for defining progress logs.

Yeah, that sounds good.

> This makes me think that it's probably better to rename ProgressMeterLogging.jl to ConsoleProgressMonitor.jl. What do you think?

TerminalProgressMonitor.jl maybe? Seems like a good name either way though.

**Comment by tkf** [comment]
OK, I renamed and re-released https://github.com/tkf/ConsoleProgressMonitor.jl/issues/2 (TerminalProgressMonitor.jl sounds good too but I thought matching with `Logging.ConsoleLogger` might make sense)

This PR should be good to go now (after passing the CI).

**Comment by pfitzseb** [comment]
Awesome, thanks!

**Pull request merged**
